version: "3.9"

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=meal_planner
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
